export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  UPLOAD: '/upload',
  REVIEW: '/review',
  REVIEW_DETAIL: '/review/:lotId/wafer/:waferId',
  COMPARE: '/compare',
  HISTORY: '/history',
  ANALYTICS: '/analytics',
  MANUAL: '/manual',
  SETTINGS: '/settings',
  SETTINGS_VENDORS: '/settings/vendors',
  SETTINGS_RULES: '/settings/rules',
  SETTINGS_SPECS: '/settings/specs',
  SETTINGS_SCORES: '/settings/scores',
} as const
